export enum ActionTypes {
  DATA_SEARCH = 'DATA_SEARCH',
  DATA_GET_SEARCH_CONTENT = 'DATA_GET_SEARCH_CONTENT',
  DATA_GET_HOME_CONTENT = 'DATA_GET_HOME_CONTENT',
  DATA_GET_COMMENTS = 'DATA_GET_COMMENTS',
  DATA_SELECT_CONTENT = 'DATA_SELECT_CONTENT',
  USER_LOGIN = 'USER_LOGIN',
  USER_ADD_COMMENT = 'USER_ADD_COMMENT',
}
